#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 298560
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#jpa 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




#pagehelper分页插件
#pagehelper分页插件pagehelper:
#  helperDialect: mysql
# reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

#模板配置
#thymeleaf:
#  cache: false
#  content-type: text/html
#  enabled: true
#  encoding: UTF-8
#  mode: HTML5
# prefix: classpath:/templates/
# suffix: .html